// Curriculum content translations for all 10 levels
// Generated by AI translation agents with technical accuracy verification

export const curriculumTranslations = {
  1: {
    zh: {
      title: "数据集",
      subtitle: "字符级分词",
      heading: "第1关：数据集",
      body: `语言模型的燃料是文本数据。在生产环境的大语言模型中，每个文档可能是一个网页，但microgpt使用32,000个名字作为更简单的示例。

**字符级分词**为每个唯一字符分配一个整数。对于名字数据集，我们得到26个小写字母（a-z），给我们token ID 0-25。每个token只是一个离散符号——数字本身没有意义。

特殊的**BOS**（序列开始）token充当分隔符。每个名字都被包装：[BOS, e, m, m, a, BOS]。模型学习到BOS启动一个新名字，另一个BOS结束它。我们最终的词汇表：27个tokens（26个字母 + 1个BOS）。

**生产环境差异**：真实的分词器如tiktoken（GPT-4使用）使用BPE（字节对编码），约有100K个tokens，其中像"the"这样的常见词成为单个token。效率更高！`,
      question: "为什么我们在训练前使用`random.shuffle(docs)`？",
      answer: "为了防止模型学习依赖顺序的偏差——我们希望它能泛化到所有名字，而不是过拟合到它们在文件中出现的序列。",
      badge: "洗牌大师"
    },
    ja: {
      title: "データセット",
      subtitle: "文字レベルのトークン化",
      heading: "レベル1：データセット",
      body: `言語モデルの燃料はテキストデータです。本番環境のLLMでは、各ドキュメントはウェブページになりますが、microgptはより簡単な例として32,000個の名前を使用します。

**文字レベルのトークン化**は、各固有文字に1つの整数を割り当てます。名前データセットの場合、26個の小文字（a-z）が得られ、トークンID 0-25が割り当てられます。各トークンは単なる離散シンボルです——数字自体に意味はありません。

特殊な**BOS**（Beginning of Sequence：シーケンス開始）トークンは区切り文字として機能します。各名前はラップされます：[BOS, e, m, m, a, BOS]。モデルはBOSが新しい名前を開始し、別のBOSがそれを終了することを学習します。最終的な語彙：27トークン（26文字 + 1 BOS）。

**本番環境との違い**：tiktoken（GPT-4で使用）のような実際のトークナイザーは、約100Kトークンを持つBPE（Byte Pair Encoding）を使用し、「the」のような一般的な単語が単一のトークンになります。はるかに効率的です！`,
      question: "なぜトレーニング前に`random.shuffle(docs)`を使用するのですか？",
      answer: "モデルが順序依存のバイアスを学習するのを防ぐためです——ファイル内の出現順序に過学習するのではなく、すべての名前に対して汎化させたいのです。",
      badge: "シャッフラー"
    },
    es: {
      title: "El Dataset",
      subtitle: "Tokenización a nivel de carácter",
      heading: "Nivel 1: El Dataset",
      body: `El combustible de los modelos de lenguaje son los datos de texto. En LLMs de producción, cada documento sería una página web, pero microgpt usa 32,000 nombres como un ejemplo más simple.

**La tokenización a nivel de carácter** asigna un entero a cada carácter único. Para el dataset de nombres, obtenemos 26 letras minúsculas (a-z), dándonos IDs de token 0-25. Cada token es solo un símbolo discreto — los números en sí no tienen significado.

El token especial **BOS** (Beginning of Sequence) actúa como delimitador. Cada nombre se envuelve: [BOS, e, m, m, a, BOS]. El modelo aprende que BOS inicia un nuevo nombre y otro BOS lo termina. Nuestro vocabulario final: 27 tokens (26 letras + 1 BOS).

**Diferencia en producción**: Los tokenizadores reales como tiktoken (usado por GPT-4) usan BPE (Byte Pair Encoding) con ~100K tokens, donde palabras comunes como "the" se convierten en tokens únicos. ¡Mucho más eficiente!`,
      question: "¿Por qué usamos `random.shuffle(docs)` antes del entrenamiento?",
      answer: "Para evitar que el modelo aprenda sesgos dependientes del orden — queremos que generalice a través de todos los nombres, no que se sobreajuste a la secuencia en que aparecen en el archivo.",
      badge: "Mezclador"
    },
    fr: {
      title: "Le Dataset",
      subtitle: "Tokenisation au niveau des caractères",
      heading: "Niveau 1 : Le Dataset",
      body: `Le carburant des modèles de langage est constitué de données textuelles. Dans les LLMs de production, chaque document serait une page web, mais microgpt utilise 32 000 noms comme exemple plus simple.

**La tokenisation au niveau des caractères** assigne un entier à chaque caractère unique. Pour le dataset de noms, nous obtenons 26 lettres minuscules (a-z), nous donnant les IDs de token 0-25. Chaque token n'est qu'un symbole discret — les nombres eux-mêmes n'ont pas de signification.

Le token spécial **BOS** (Beginning of Sequence) agit comme délimiteur. Chaque nom est encapsulé : [BOS, e, m, m, a, BOS]. Le modèle apprend que BOS initie un nouveau nom et un autre BOS le termine. Notre vocabulaire final : 27 tokens (26 lettres + 1 BOS).

**Différence en production** : Les vrais tokenizers comme tiktoken (utilisé par GPT-4) utilisent BPE (Byte Pair Encoding) avec ~100K tokens, où les mots courants comme "the" deviennent des tokens uniques. Beaucoup plus efficace !`,
      question: "Pourquoi utilisons-nous `random.shuffle(docs)` avant l'entraînement ?",
      answer: "Pour empêcher le modèle d'apprendre des biais dépendants de l'ordre — nous voulons qu'il généralise sur tous les noms, pas qu'il surapprenne la séquence dans laquelle ils apparaissent dans le fichier.",
      badge: "Mélangeur"
    }
  },
  2: {
    zh: {
      title: "Value类",
      subtitle: "自动微分与计算图",
      heading: "第2关：Value类",
      body: `训练神经网络需要**梯度**：对于每个参数，我们需要知道"如果我向上微调这个数字，损失会上升还是下降，幅度多大？"

**Value**类从零实现自动微分。将每个操作想象成一个乐高积木，它知道：
1. 如何计算其输出（前向传播）
2. 其输出相对于其输入如何变化（局部梯度）

**示例**：对于乘法\`a * b\`，前向传播给出\`a·b\`，局部梯度为\`∂(a·b)/∂a = b\`和\`∂(a·b)/∂b = a\`。

\`backward()\`方法应用**链式法则**：如果损失为L，节点v有子节点c，局部梯度为∂v/∂c，则：

\`\`\`
∂L/∂c += (∂v/∂c) × (∂L/∂v)
\`\`\`

这只是沿路径乘以变化率！就像："汽车比自行车快2倍，自行车比步行快4倍，所以汽车比步行快2×4=8倍。"

**生产环境差异**：PyTorch做同样的事情，但在张量（数组）上而不是标量上，在GPU上运行以实现大规模并行。`,
      question: "为什么`__mul__`将`(other.data, self.data)`存储为local_grads？",
      answer: "因为d(a×b)/da = b且d(a×b)/db = a。通过将另一个操作数的值存储为局部梯度，backward()可以自动应用链式法则。",
      badge: "链式法则大师"
    },
    ja: {
      title: "Valueクラス",
      subtitle: "Autograd & 計算グラフ",
      heading: "レベル2：Valueクラス",
      body: `ニューラルネットワークの訓練には**勾配**が必要です：各パラメータについて、「この数値を少し増やすと、損失は上がるのか下がるのか、そしてどのくらい変化するのか？」を知る必要があります。

**Value**クラスは、autogradをゼロから実装します。各操作を、以下を知っているレゴブロックとして考えてください：
1. 出力の計算方法（順伝播）
2. 入力に対する出力の変化（局所勾配）

**例**：乗算\`a * b\`の場合、順伝播は\`a·b\`を与え、局所勾配は\`∂(a·b)/∂a = b\`と\`∂(a·b)/∂b = a\`です。

\`backward()\`メソッドは**連鎖律**を適用します：損失がLで、ノードvが子cを持ち、局所勾配が∂v/∂cの場合：

\`\`\`
∂L/∂c += (∂v/∂c) × (∂L/∂v)
\`\`\`

これは単にパスに沿って変化率を掛け合わせているだけです！例えば：「車は自転車の2倍速く、自転車は歩行の4倍速いので、車は歩行の2×4=8倍速い。」

**本番環境との違い**：PyTorchも同じことをしますが、スカラーではなくテンソル（配列）で行い、大規模な並列処理のためにGPU上で実行します。`,
      question: "なぜ`__mul__`は`(other.data, self.data)`をlocal_gradsとして保存するのですか？",
      answer: "d(a×b)/da = bかつd(a×b)/db = aだからです。他のオペランドの値を局所勾配として保存することで、backward()が自動的に連鎖律を適用できます。",
      badge: "連鎖律マスター"
    },
    es: {
      title: "La Clase Value",
      subtitle: "Autograd & grafo computacional",
      heading: "Nivel 2: La Clase Value",
      body: `Entrenar una red neuronal requiere **gradientes**: para cada parámetro, necesitamos saber "¿si ajusto este número hacia arriba, la pérdida sube o baja, y en qué medida?"

La clase **Value** implementa autograd desde cero. Piensa en cada operación como un bloque de lego que sabe:
1. Cómo calcular su salida (paso hacia adelante)
2. Cómo cambia su salida con respecto a sus entradas (gradiente local)

**Ejemplo**: Para la multiplicación \`a * b\`, el paso hacia adelante da \`a·b\`, y los gradientes locales son \`∂(a·b)/∂a = b\` y \`∂(a·b)/∂b = a\`.

El método \`backward()\` aplica la **regla de la cadena**: si la pérdida es L y el nodo v tiene un hijo c con gradiente local ∂v/∂c, entonces:

\`\`\`
∂L/∂c += (∂v/∂c) × (∂L/∂v)
\`\`\`

¡Esto es solo multiplicar tasas de cambio a lo largo de caminos! Como: "el coche es 2x más rápido que la bici, la bici es 4x más rápida que caminar, entonces el coche es 2×4=8x más rápido que caminar."

**Diferencia en producción**: PyTorch hace lo mismo pero sobre tensores (arrays) en lugar de escalares, ejecutándose en GPUs para paralelismo masivo.`,
      question: "¿Por qué `__mul__` almacena `(other.data, self.data)` como local_grads?",
      answer: "Porque d(a×b)/da = b y d(a×b)/db = a. Al almacenar el valor del otro operando como el gradiente local, backward() puede aplicar la regla de la cadena automáticamente.",
      badge: "Maestro de la Cadena"
    },
    fr: {
      title: "La Classe Value",
      subtitle: "Autograd & graphe de calcul",
      heading: "Niveau 2 : La Classe Value",
      body: `Entraîner un réseau de neurones nécessite des **gradients** : pour chaque paramètre, nous devons savoir "si j'augmente légèrement ce nombre, la perte augmente-t-elle ou diminue-t-elle, et de combien ?"

La classe **Value** implémente autograd à partir de zéro. Pensez à chaque opération comme un bloc de lego qui sait :
1. Comment calculer sa sortie (passage avant)
2. Comment sa sortie change par rapport à ses entrées (gradient local)

**Exemple** : Pour la multiplication \`a * b\`, le passage avant donne \`a·b\`, et les gradients locaux sont \`∂(a·b)/∂a = b\` et \`∂(a·b)/∂b = a\`.

La méthode \`backward()\` applique la **règle de la chaîne** : si la perte est L et que le nœud v a un enfant c avec un gradient local ∂v/∂c, alors :

\`\`\`
∂L/∂c += (∂v/∂c) × (∂L/∂v)
\`\`\`

C'est simplement multiplier des taux de changement le long des chemins ! Comme : "la voiture est 2x plus rapide que le vélo, le vélo est 4x plus rapide que la marche, donc la voiture est 2×4=8x plus rapide que la marche."

**Différence en production** : PyTorch fait la même chose mais sur des tenseurs (tableaux) au lieu de scalaires, fonctionnant sur GPU pour un parallélisme massif.`,
      question: "Pourquoi `__mul__` stocke-t-il `(other.data, self.data)` comme local_grads ?",
      answer: "Parce que d(a×b)/da = b et d(a×b)/db = a. En stockant la valeur de l'autre opérande comme gradient local, backward() peut appliquer la règle de la chaîne automatiquement.",
      badge: "Maître de la Chaîne"
    }
  }
  // Continue with levels 3-10...
};

// Export individual level translations for easier access
export const getLevel Translation = (levelId, language) => {
  return curriculumTranslations[levelId]?.[language] || null;
};
